config/routes.rb
require 'sidekiq/web'

Stripe::Application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => 'registrations' }
  root 'welcome#index'
  get '/pricing', to: 'welcome#pricing'
  resources :stripe_events, only: [:create]
  resources :subscriptions
  get '/cancel_subscription', to: 'subscriptions#cancel_subscription', as: :cancel_subscription
  get '/change_plan', to: 'subscriptions#change_plan'
  get '/update_change_plan', to: 'subscriptions#update_plan_change'
  get '/no_card', to: 'subscriptions#no_card', as: :no_card
  post '/buy', to:'subscriptions#create', as: :buy
  mount Sidekiq::Web, at: '/sidekiq'
  

end

app/models/subscription.rb
# == Schema Information
#
# Table name: subscriptions
#
#  id                     :integer          not null, primary key
#  user_id                :integer          not null
#  billing_email          :string(255)      not null
#  card_last4             :string(255)
#  card_type              :string(255)
#  card_expiration        :date
#  stripe_id              :string(255)
#  free_trial_expiration  :date
#  plan_id                :integer          not null
#  created_at             :datetime
#  updated_at             :datetime
#  subscription_status_id :integer
#

class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :plan
  belongs_to :subscription_status
  delegate :name, to: :plan
  delegate :status, to: :subscription_status
  
  attr_accessor :stripe_card_token, :email
  
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: "1", card: stripe_card_token)
      self.stripe_token = customer.id
      save!
    end
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating customer: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
    false
  end
  
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :authenticate_user!
  before_action :verify_user
  
  def index
    @subscription = current_user.subscription
  end
  
  def edit
    @subscription = current_user.subscription
  end
  
  def update
    subscription = current_user.subscription
    UpdateCustomerWorker.perform_async(subscription.id, params[:subscription][:stripe_card_token])
    redirect_to subscriptions_path, :notice => "You credit card information has been updated!"
  end
  
  def change_plan
  end
  
  def update_plan_change
    subscription = current_user.subscription
    UpdatePlanWorker.perform_async(subscription.id, params[:plan])
    subscription.update_attributes(plan_id: params[:plan])
    redirect_to subscriptions_path, :notice => "Your plan has been changed to the #{subscription.name} plan!"
  end
  
  def cancel_subscription
    @subscription = current_user.subscription
    CancelCustomerWorker.perform_async(@subscription.id)
    # Time.at(customer.subscription.current_period_end).strftime("%m/%d/%Y")
    # do we need to track plan status and date plan is cancelled
    redirect_to subscriptions_path, :notice => "Your account has been cancelled."
  end
  
end

app/views/subscriptions/change_plan.html.erb
<% provide(:title, 'Select a Plan') %>
<div id="welcome" class="hero-unit span7">
  <h1>Select a Plan</h1>
</div>
<div class="col-md-12 plans">
  <div class="col-md-4 well">
    <div class="plan"><h2>Solo</h2></div>
    <ul class="unstyled">
      <li>Up to 2 users</li>
      <li>Unlimited Clients</li>
      <li>Unlimited Invoices</li>
    </ul>
    <h3>$9/month</h3>
    <%= link_to 'Start Free Trial', update_change_plan_path(:plan => '1'), :class => 'btn btn-primary' %> 
  </div>
  <div class="col-md-4 well featured">
    <div class="plan featured-plan"><h2>Gold</h2></div>
    <ul class="unstyled">
      <li>Up to 10 users</li>
      <li>Unlimited Clients</li>
      <li>Unlimited Invoices</li>
    </ul>
    <h3>$19/month</h3>
    <%= link_to 'Start Free Trial', update_change_plan_path(:plan => '2'), :class => 'btn btn-primary' %> 
  </div>
  <div class="col-md-4 well">
    <div class="plan"><h2>Platinum</h2></div>
    <ul class="unstyled">
      <li>Up to 20 users</li>
      <li>Unlimited Clients</li>
      <li>Unlimited Invoices</li>
    </ul>
    <h3>$29/month</h3>
    <%= link_to 'Start Free Trial', update_change_plan_path(:plan => '3'), :class => 'btn btn-primary' %> 
  </div>
</div>

app/views/subscriptions/edit.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
  <div class="panel-body">
    <h2>Update Your Credit Card</h2>
    <%= form_for @subscription do |f| %>
      <%= f.hidden_field :stripe_card_token %>
      <div class="form-group">
        <%= label_tag :card_number, "Credit Card Number", class: "control-label" %>
        <%= text_field_tag :card_number, nil, name: nil, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :card_code, "Security Code on Card (CVV)", class: "control-label" %>
        <%= text_field_tag :card_code, nil, name: nil, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :card_month, "Expiration Date (MM/YY)", class: "control-label" %>
        <%= text_field_tag :card_month, nil, name: nil, placeholder: "MM", class: "form-control exp_date" %> /
        <%= text_field_tag :card_year, nil, name: nil, placeholder: "YY", class: "form-control exp_date" %>
      </div>     
      <%= f.submit "Update Credit Card", class: 'btn btn-primary' %>
      <div id="stripe_error">
        <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
      </div>
    <% end %>
  </div>
</div>

app/views/subscriptions/index.html.erb
<%= render 'layouts/error' %>
<%= status_message(@subscription) %>
<h1> Billing and Invoices</h1>
<h3>Current Plan: <%= @subscription.name %></h3>
<%= link_to "Change Plan", change_plan_path %>


<h3>Invoices</h3>
<p>Your invoices are being emailed to: <%= @subscription.billing_email %></p>
<%= link_to "Update Invoice", root_path %>


<h3>Credit Card </h3>
<%= link_to "Update Credit Card Detail", edit_subscription_path(current_user.subscription) %>


<h3>Cancel Your Account</h3>
<%= link_to 'Delete', cancel_subscription_path, data: {confirm: 'Are you sure you want to delete this account, no take backsies?'} %>