config/routes.rb
require 'sidekiq/web'

Stripe::Application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => 'registrations' }
  root 'welcome#index'
  get '/pricing', to: 'welcome#pricing'
  resources :stripe_events, only: [:create]
  resources :subscriptions
  get '/cancel_subscription', to: 'subscriptions#cancel_subscription', as: :cancel_subscription
  get '/change_plan', to: 'subscriptions#change_plan'
  get '/update_change_plan', to: 'subscriptions#update_plan_change'
  get '/no_card', to: 'subscriptions#no_card', as: :no_card
  post '/buy', to:'subscriptions#create', as: :buy
  mount Sidekiq::Web, at: '/sidekiq'
  

end

app/helpers/layout_helper.rb
module LayoutHelper
  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash_#{name}")
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end
end

app/views/layouts/_error.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= flash_class type%>">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="container">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Stripe', root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <%= render "layouts/navbar_right" %>   
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/_navbar_right.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
    <li><%= link_to "Logged in as " + current_user.email, edit_user_registration_path %></li></li>
    <li><%= link_to "Subscription", subscriptions_path %></li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Features", root_path %></li>
    <li><%= link_to "Pricing", pricing_path %></li>
    <li><%= link_to "Sign Up", pricing_path %></li>
    <li><%= link_to "Login", new_user_session_path %></li>
  <% end %>
</ul>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "https://js.stripe.com/v1/", "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= yield :scripts %>
    </div>
  </body>
</html>